### ISSUE TITLE
make install should honour DESTDIR and configuration options 

### ISSUE THREAD

**Issue by treinen** [OCamlPro-Iguernlala/ocplib-simplex#3]
Hi, the install target of your Makefile just does an "ocamlfind install", which usually installs in /usr/local/lib, regardless of $(DESTDIR), and the options used for ./configure.

For the debian package I am using the attached patch, which you might want to adopt for your release.

Cheers 

-Ralf.

```
Index: ocplib-simplex/Makefile.in
===================================================================
--- ocplib-simplex.orig/Makefile.in	2016-11-25 07:16:31.462449248 +0100
+++ ocplib-simplex/Makefile.in	2016-11-25 07:18:03.262827029 +0100
@@ -13,11 +13,11 @@
 # (enclosed in the file LGPL).
 
 # where to install the binaries
-# DESTDIR=
+DESTDIR=
 # prefix=@prefix@
 # exec_prefix=@exec_prefix@
 # BINDIR=$(DESTDIR)@bindir@
-# LIBDIR=$(DESTDIR)@libdir@/ocplib-simplex
+LIBDIR=$(DESTDIR)@OCAMLLIB@/
 # DATADIR=$(DESTDIR)@datadir@/ocplib-simplex
 
 # where to install the man page
@@ -112,7 +112,8 @@
 ##############
 
 install: all META
-	ocamlfind install ocplib-simplex src/$(LIBNAME).* src/*.mli META
+	OCAMLFIND_DESTDIR=$(LIBDIR) \
+	  ocamlfind install ocplib-simplex src/$(LIBNAME).* src/*.mli META
 ```

**Comment by iguerNL** [comment]
Thanks. I've just patched the Makefile!

I didn't notice the issue because the installation works well with ocamlfind + OPAM

**Comment by treinen** [comment]
Thanks, but please be aware that "make install" nows installs in /usr/lib/ocaml, or whatever the
standard ocaml library directory is on your system. I am not sure this is what you want ...

-Ralf.
