### ISSUE TITLE
Assert false raised at line 241 in solveBounds.ml

### ISSUE THREAD

**Issue by Stevendeo** [OCamlPro-Iguernlala/ocplib-simplex#33]
TL;DR : maximizing on some environments leads to a critical failure.

The following script tries to maximize the polynomial 100 \* v1 + 100 \* v2 with v1 >= 0, v2 >= 0 and 2 \* v1 + 2 \* v2 <= 3, which is possible on Z (v1 = 1, v2 = 0) . But instead of returning something, it leads to an `assert false`: 

```
module Var = struct
  include String
  let is_int _r = true
  let print = Format.pp_print_string
end

module Z = struct
  include Z
  let m_one = Z.sub Z.zero Z.one
  let is_zero = Z.equal Z.zero
  let is_one = Z.equal Z.one
  let is_m_one = Z.equal m_one
  let sign x = Z.compare x Z.zero
  let mult = Z.mul
  let is_int _ = true
  let minus = Z.neg
  let floor = Fun.id
  let ceiling = Fun.id
  let print = Z.pp_print
end

module Explanation = struct
  type t = unit
  let empty = ()
  let union _ _ = ()
  let print _ _ = ()
end

module Sim = OcplibSimplex.Basic.Make(Var)(Z)(Explanation)

let bound_of_z (z : Z.t) : Sim.Core.bound =
  {bvalue = Sim.Core.R2.of_r z; explanation = ()}

let zero_bound = bound_of_z Z.zero

let var ?min ?max name core = fst @@ Sim.Assert.var core ?min ?max name

let poly ?min ?max poly name core = fst @@ Sim.Assert.poly core poly ?min ?max name

let maximize p core = Sim.Solve.maximize core p

let trigger_bug () =
  let core = Sim.Core.empty ~is_int:true ~check_invs:false in
  core
  |> var ~min:zero_bound "v1"
  |> var ~min:zero_bound "v2"
  |> poly
    ~max:(bound_of_z @@ Z.of_int 3)
    (Sim.Core.P.from_list [
        "v1", Z.of_int 2;
        "v2", Z.of_int 2;
      ])
    "poly"
  |> maximize (Sim.Core.P.from_list [
      "v1", Z.of_int 100;
      "v2", Z.of_int 100;
    ]
    )

let () = ignore @@ trigger_bug ()
```

**Comment by bclement-ocp** [comment]
The simplex algorithm does not work on integers, it only works on rationals and reals. In particular, the equation `mul y (div x y) = x` must hold on the value type.

To find integer solutions, the results of the simplex must be filtered (see branch-and-cut algorithms) to eliminate non-integer solutions from the rational solutions, but this library currently does not provide such facilities.

(Edit: to clarify, this can be done by writing user code outside of the library, but is not a functionality provided by the library)

**Comment by Stevendeo** [comment]
I changed the `is_int` function in `Var` to fun _ -> false and the empty core with `is_int:false` but the same bug is triggered, what am I missing?

**Comment by Stevendeo** [comment]
Perhaps only Q would be suited in instead of the Z module?

**Comment by Stevendeo** [comment]
Okay it works! But I still have an assertion failure when I remove from the script the v2 variable.

**Comment by bclement-ocp** [comment]
The type given as second parameter to `MakeBasic` must be able to represent rational values, so you should use `Q` instead of `Z`. The `is_int` function/parameters (both must be set iirc) tell the solver you are only interested in integer solutions (represented as rationals) and enables some simplifications, but does not guarantee that only integer solutions will be returned.

**Comment by bclement-ocp** [comment]
> Okay it works! But I still have an assertion failure when I remove from the script the v2 variable.

Can you provide the exact code that raises the assertion?

**Comment by Stevendeo** [comment]
Same script except for `trigger_bug` : 

```

let trigger_bug () =
  let core = Sim.Core.empty ~is_int:false ~check_invs:false in
  core
  |> var ~min:(bound_of_q Q.zero) "v1"
  |> poly
    ~max:(bound_of_q @@ Q.of_int 3)
    (Sim.Core.P.from_list [
        "v1", Q.of_int 2;
      ])
    "m"
  |> maximize (Sim.Core.P.from_list [
      "v1", Q.of_int 100;
    ]
    )
```

**Comment by bclement-ocp** [comment]
The assert that gets triggered in this case is because `poly` expects a polynomial with at least two variables but you are passing a single variable (see assert [here](https://github.com/OCamlPro/ocplib-simplex/blob/d0c0a04561c0043a723c7985e0fd5d6f3bda260a/src/assertBounds.ml#L222)). `var` must be used instead of `poly` in this case, since a slack variable is not needed.

I agree that this is not very user-friendly; it should be documented and use `invalid_arg` for a better error message.
