### ISSUE TITLE
please clarify License

### ISSUE THREAD

**Issue by treinen** [OCamlPro-Iguernlala/ocplib-simplex#4]
Hello,

LICENCE says in the first paragraph:

... with some exceptions as defined for the OCaml Core System (see https://github.com/ocaml/ocaml/blob/trunk/LICENSE)

I have no idea what that means for the licence of your library. Please clarify:
- if it is not relevant, then please drop it
- if it is relevant, then please include the exception, properly adapted to the case of your library.

Thanks -Ralf.

**Comment by iguerNL** [comment]
I was talking about "OCaml static linking exception" as described in OCaml LICENCE and here: https://caml.inria.fr/ocaml/license.en.html

**Comment by iguerNL** [comment]
I clarified Licence like this:
- https://github.com/OCamlPro-Iguernlala/ocplib-simplex/blob/master/README.md#licensing
- https://github.com/OCamlPro-Iguernlala/ocplib-simplex/blob/master/LICENSE

It should be OK now.
@lefessan

**Comment by treinen** [comment]
Thanks ! -Ralf.
