### ISSUE TITLE
Package doesn't contain a configure

### ISSUE THREAD

**Issue by kanigsson** [OCamlPro-Iguernlala/ocplib-simplex#9]
Hello,

We have seen that the distributed package doesn't contain a configure script. This is a nuisance for us as we build ocplib-simplex on both windows and linux and on windows it's not obvious to get autoconf working.

We currently work around this situation by packaging a modified ocplib-simplex package in our build system, which contains a pre-generated configure. But it would be simpler for us if the official package directly contained the configure script. Note that this would also require changes in the opam package.

Would it be possible to add the configure script to the package?

**Comment by iguerNL** [comment]
Hi @kanigsson,

There is no configure because releases are done directly via Github tagging facilities, and it's not a good idea to commit the generated configure file.

**Comment by kanigsson** [comment]
Hello @OriginLabs-Iguernlala ,

I know, so my request would require you to change your process and prepare the release tarballs outside of github. Is that at all possible?

**Comment by iguerNL** [comment]
I'll try to think about it for the next release :-)

**Comment by Stevendeo** [comment]
The library now only requires `dune` to be compiled, we will release the new version soon, along with the next alt-ergo version. Does that solve your problem @kanigsson ?

**Comment by kanigsson** [comment]
Yes, I believe it does, thank you.
